disabled_rules:
  - line_length
  - multiple_closures_with_trailing_closure
  - notification_center_detachment

excluded:
  - Pods

identifier_name:
  excluded:
    - wc

# line_length:
#  - 120 # warning
#  - 240 # error